package com.sureprep.dating.util

val DATA_USERS = "Users"
val DATA_NAME = "name"
val DATA_EMAIL = "email"
val DATA_AGE = "age"
val DATA_GENDER = "gender"
val DATA_GENDER_PREFERENCE = "preferredGender"
val GENDER_MALE = "male"
val GENDER_FEMALE = "female"
val GENDER_NB = "nonbinary"
val DATA_CPA = "CPA"
val DATA_TAXPAYER = "Taxpayer"
val DATA_PROFESSIONAL_STATUS = "professionalStatus"
val DATA_DESCRIPTION = "description"
val DATA_IMAGE_URL = "imageUrl"
val DATA_SWIPES_LEFT = "swipesLeft"
val DATA_SWIPES_RIGHT = "swipesRight"
val DATA_MATCHES = "matches"

val DATA_CHATS = "Chats"
val DATA_MESSAGES = "Messages"